name: CI-CD Pipeline

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write   # ðŸ”´ REQUIRED FOR WORKLOAD IDENTITY

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/708132204852/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
          service_account: "github-actions-sa@devops-k8s-assignment-483517.iam.gserviceaccount.com"

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: devops-k8s-assignment-483517

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      - name: Build Docker image
        run: |
          docker build -t us-central1-docker.pkg.dev/devops-k8s-assignment-483517/hello-repo/hello-app:latest -f app/Dockerfile .

      - name: Push Docker image
        run: |
          docker push us-central1-docker.pkg.dev/devops-k8s-assignment-483517/hello-repo/hello-app:latest

      - name: Get GKE credentials
        run: |
          gcloud container clusters get-credentials devops-gke \
            --region us-central1 \
            --project devops-k8s-assignment-483517

      - name: Deploy to GKE
        run: |
          kubectl apply -f k8s/
